In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('data/training_final_latcorr.csv')

In [5]:
df

,field_1,Name,Longitude,Latitude,CO2 (mg C m¯² d¯¹),CH4 (mg C m-2 d-1),CO2 (g/kWh),CH4 (g/kWh),Area / Electricity,Area_km2,...,npp_annual_avg,npp_spring_avg_lc,npp_spring_avg,npp_summer_avg_lc,npp_summer_avg,npp_fall_avg_lc,npp_fall_avg,npp_winter_avg_lc,npp_winter_avg,erosion
0,116,Segredo,-52.100000,-25.783333,600.0,29.9,15.167696,0.274857,0.018889,82.0,...,200.500000,212.000000,207.666672,202.000000,180.333328,207.666672,212.000000,180.333328,202.000000,21.503389
1,117,Segredo,-52.100000,-25.783333,1306.1,5.0,33.017545,0.045963,0.018889,82.0,...,200.500000,212.000000,207.666672,202.000000,180.333328,207.666672,212.000000,180.333328,202.000000,21.503389
2,45,Itaipu,-54.550000,-25.383333,328.6,NaN,6.603175,NaN,0.015015,1350.0,...,87.000000,79.000000,85.333336,87.000000,96.666664,85.333336,79.000000,96.666664,87.000000,32.145058
3,104,RibeirÃ£o das Lages,-43.883333,-22.700000,22.1,NaN,NaN,NaN,NaN,30.0,...,151.416672,153.333328,179.333328,156.666672,170.666672,179.333328,153.333328,170.666672,156.666672,0.541019
4,7,Barra Bonita,-48.583333,-22.516667,1036.4,9.9,3187.260766,11.071149,2.297872,324.0,...,132.750000,94.000000,166.000000,130.000000,141.000000,166.000000,94.000000,141.000000,130.000000,7.974369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,68,Lule,21.666667,65.833333,12.3,NaN,20.541089,NaN,1.247826,574.0,...,99.250000,NaN,58.333332,NaN,180.333328,NaN,51.333332,NaN,107.000000,0.004779
150,66,Lokka,27.733333,67.816667,545.5,79.0,632.052667,33.285333,0.865753,316.0,...,95.583336,NaN,47.666668,NaN,114.000000,NaN,39.666668,NaN,181.000000,0.001489
151,67,Lokka,27.733333,67.816667,288.0,115.0,333.696000,48.453333,0.865753,316.0,...,95.583336,NaN,47.666668,NaN,114.000000,NaN,39.666668,NaN,181.000000,0.001489
152,100,Porttipahta,26.750000,68.000000,572.7,13.0,1623.991970,13.405017,2.118812,214.0,...,90.250000,NaN,46.333332,NaN,122.000000,NaN,40.666668,NaN,181.000000,0.010603
153,101,Porttipahta,26.750000,68.000000,420.0,6.0,1190.984158,6.186931,2.118812,214.0,...,90.250000,NaN,46.333332,NaN,122.000000,NaN,40.666668,NaN,181.000000,0.010603

In [ ]:
#random forest does not need scaling

#distance-based methods such as knn require scaling
#linear regression needs scaling
#svm needs scalaling

In [7]:
df.rename(columns = {'CH4 (mg C m-2 d-1)':'CH4', 'CO2 (mg C m¯² d¯¹)':'CO2'}, inplace = True)

In [8]:
df.columns

Index(['field_1', 'Name', 'Longitude', 'Latitude', 'CO2', 'CH4', 'CO2 (g/kWh)',
       'CH4 (g/kWh)', 'Area / Electricity', 'Area_km2', 'Age', 'Volume_km3',
       'Areakm2_div_Volkm3', 'org_c', 'temp_annual_avg', 'temp_spring_avg_lc',
       'temp_spring_avg', 'temp_summer_avg_lc', 'temp_summer_avg',
       'temp_fall_avg_lc', 'temp_fall_avg', 'temp_winter_avg_lc',
       'temp_winter_avg', 'NDVI_annual_avg', 'NDVI_spring_avg_lc',
       'NDVI_spring_avg', 'NDVI_summer_avg_lc', 'NDVI_summer_avg',
       'NDVI_fall_avg_lc', 'NDVI_fall_avg', 'NDVI_winter_avg_lc',
       'NDVI_winter_avg', 'npp_annual_avg', 'npp_spring_avg_lc',
       'npp_spring_avg', 'npp_summer_avg_lc', 'npp_summer_avg',
       'npp_fall_avg_lc', 'npp_fall_avg', 'npp_winter_avg_lc',
       'npp_winter_avg', 'erosion'],
      dtype='object')